// <auto-generated />
namespace Mahan.Stations.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeTypeOfFlightRemarkTypeAndFuellingTypeToFixedEntityBase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeTypeOfFlightRemarkTypeAndFuellingTypeToFixedEntityBase));
        
        string IMigrationMetadata.Id
        {
            get { return "201510181054335_ChangeTypeOfFlightRemarkTypeAndFuellingTypeToFixedEntityBase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
