// <auto-generated />
namespace Selonia.Accounting.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSegmentSetting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSegmentSetting));
        
        string IMigrationMetadata.Id
        {
            get { return "201607221657314_AddSegmentSetting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
