//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mahan.Tralus.Stations.Migration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mahan.Tralus.Stations.Migration.SqlResource", typeof(SqlResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if OBJECT_ID(&apos;{0}&apos;) IS NOT NULL
        ///	DROP VIEW Stations.FlightReportView;.
        /// </summary>
        internal static string DropViewIfExists {
            get {
                return ResourceManager.GetString("DropViewIfExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE VIEW Stations.FlightReportView
        ///AS
        ///SELECT
        ///	FL.Id										Id,
        ///	FL.Id										FlightLegId,
        ///	FL.[Status],
        ///	FL.FlightNumberId,
        ///	FL.FlightTypeId,
        ///	FL.AircraftRegisterId,
        ///	FL.AircraftTypeId,
        ///	FL.DepartureAirportId,
        ///	FL.ArrivalAirportId,
        ///
        ///	FL.ScheduledDepartureDateTime_AltCalendarDayUtc,
        ///	FL.ScheduledDepartureDateTime_AltCalendarMonthUtc,
        ///	FL.ScheduledDepartureDateTime_AltCalendarYearUtc,
        ///	FL.ScheduledDepartureDateTime_DateHome,
        ///	FL.ScheduledDepartureDateTime_DateLocal,
        ///	FL.ScheduledDepar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FlightReportView {
            get {
                return ResourceManager.GetString("FlightReportView", resourceCulture);
            }
        }
    }
}
